description: Prepares the repo for a typical CI job

name: Prepare
inputs:
  node-version: # id of input
    description: 'Node.js version'
    required: false
    default: '20'

runs:
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org
        cache: 'npm'
    - name: Install dependencies
      uses: bahmutov/npm-install@3e063b974f0d209807684aa23e534b3dde517fd9 # v1.11.2
      with:
        install-command: npm ci --foreground-scripts
  using: composite
