description: Prepares the repo for a typical CI job

name: Prepare
inputs:
  node-version: # id of input
    description: 'Node.js version'
    required: false
    default: '20'

runs:
  steps:
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      uses: bahmutov/npm-install@3714964fb879ebbbc108e167f0f3a0c81ec075c9 # v1.10.10
      with:
        install-command: npm ci --foreground-scripts
  using: composite
