description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        node-version: '20'
    - name: Install dependencies
      uses: bahmutov/npm-install@2509f13e8485d88340a789a3f7ca11aaac47c9fc # v1.8.36
      with:
        install-command: npm ci --foreground-scripts
  using: composite
